# -*- coding: utf-8 -*-
"""Zadania_1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-FeLCCbNNv0zYcHB2SdEh_NtjnQ8NIz
"""

#zad1
k = open("data.fasta","r")
data = k.read()
data = data.split(">")
ids = []
for i in range(len(data)):
  if "_" in data[i]:
    ids.append(data[i].split(" ")[0])
for i in range(len(data)):
  data[i] = data[i].split("\n")
  data[i] = data[i][1:]
  data[i] = "".join(data[i])
updated_data = list(filter(None, data))
slownik = {}
for i, id in enumerate(updated_data):
  if "M" in id:
    slownik[ids[i]] = len(updated_data[i])
print(slownik)

#zad2
rule_table = {(1,1,1):0, (1,1,0):1, (1,0,1):1, (1,0,0):0, (0,1,1):1, (0,1,0):1, (0,0,1):1, (0,0,0):0}
WIDTH, HEIGHT = 1024,788 # liczba komórek w generacji, liczba generacji np. 500,500
grid = [[0 for _ in range(WIDTH)] for _ in range(HEIGHT)]
grid[0][-1] = 1

for i in range(HEIGHT - 1):
  for j in range(1,WIDTH - 1):
    grid[i+1][j] = rule_table[(grid[i][j-1],grid[i][j],grid[i][j+1])]
f = open("zad2.ppm","w+")
f.write("P3\n")
f.write(str(WIDTH) + " " + str(HEIGHT) + "\n")
f.write("255\n")
for i in range(HEIGHT):
  for j in range(WIDTH):
    f.write(str(grid[i][j]) + " ")
  f.write("\n")
f.close()